# Generated by Django 2.2 on 2019-04-09 15:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190409_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
